xrite helle
RajaBellebon/photo-website-test pull request #3
Opened 2020-10-05 09:07 UTC by christbel

2020-10-07 05:23 UTC, RajaBellebon requested changes

2020-10-07 05:23 UTC, RajaBellebon commented on challenge.py
> +#TOO
Coucou,

C'est bien tu as ete capable de faire ta premier PR...

Maintenant passons a la revue.

2020-10-07 05:23 UTC, RajaBellebon commented on challenge.py
> +#TOO
Remove #TODO

2020-10-07 05:23 UTC, RajaBellebon commented on challenge.py
> +print ("Hello")
Add a new empty line at the end of the file

2020-10-13 22:15 UTC, RajaBellebon approved these changes

2020-10-13 22:17 UTC, RajaBellebon commented on challenge.py
> +print ("Hello")
Pour etre honnete le mieux ca aurait ete de faire

```
print("Hello")

```
generalement, tu laisses toujours un espace / un saut de ligne a la fin de ton fichier.

2020-10-13 22:17 UTC, RajaBellebon approved these changes

2020-10-14 21:27 UTC, merged

2020-10-14 21:34 UTC, christbel commented
Ok je men occuperai demain car je suis au dodo... Mdr
Bisous


Le mer. 14 oct. 2020 à 22:27, Raja Bellebon <notifications@github.com> a
écrit :

> Merged #3 <https://github.com/RajaBellebon/photo-website-test/pull/3>
> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/RajaBellebon/photo-website-test/pull/3#event-3878595974>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO5KMLBSIIG4GEJYLX7BQVDSKYJUHANCNFSM4SENLXCA>
> .
>